//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightFinalSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Airport
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int AirportID { get; set; }


        [Required]
        [StringLength(30, MinimumLength = 3, ErrorMessage = "Plase enter valid value!")]
        public string AirportName { get; set; }

        [Required]
        [StringLength(20, MinimumLength = 3, ErrorMessage = "Plase enter valid value!")]
        public string AirportCountry { get; set; }

        [Required]
        [StringLength(20, MinimumLength = 3, ErrorMessage = "Plase enter valid value!")]
        public string AirportCity { get; set; }

        [Required]
        [RegularExpression(@"[A-Z]{3,3}", ErrorMessage = "Plase enter valid value!")]
        public string AirportAbbre { get; set; }
    }
}
