//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightFinalSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Passenger
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int PassengerID { get; set; }

        [Required]
        [StringLength(20, MinimumLength = 2, ErrorMessage = "Plase enter valid value!")]
        public string PassengerName { get; set; }

        [Required]
        [StringLength(20, MinimumLength = 2, ErrorMessage = "Plase enter valid value!")]
        public string PassengerSurname { get; set; }

        [Required]
        [RegularExpression(@"[+]([0-9]{7,19})", ErrorMessage = "Plase enter valid value!")]
        public string PassengerTel { get; set; }

        [DataType(DataType.Date), DisplayFormat(DataFormatString = @"{0:dd\/MM\/yyyy}",
           ApplyFormatInEditMode = true)]
        public System.DateTime PassengerBirthDate { get; set; }
    }
}
