//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightFinalSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Plane
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plane()
        {
            this.Route = new HashSet<Route>();
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int PlaneID { get; set; }


        [Required]
        [StringLength(15, MinimumLength = 2, ErrorMessage = "Plase enter valid value!")]
        public string PlaneName { get; set; }

        [Required]
        [StringLength(10, MinimumLength = 3, ErrorMessage = "Plase enter valid value!")]
        public string PlaneType { get; set; }

        [Required]
        [Range(0, 400, ErrorMessage = "Plase enter valid value!")]
        public int PlaneCapacity { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Route> Route { get; set; }
    }
}
