//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightFinalSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Route
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int RouteID { get; set; }

        [RegularExpression(@"([A-Z]{2,2})-([0-9]{4,4})", ErrorMessage = "Plase enter valid value!")]
        public string RouteFlightNumber { get; set; }

        public int RoutePlaneID { get; set; }
        public string RouteDepAirport { get; set; }
        public string RouteArrAirport { get; set; }

        [DataType(DataType.Date), DisplayFormat(DataFormatString = @"{0:dd\/MM\/yyyy}",
           ApplyFormatInEditMode = true)]
        public System.DateTime RouteDepDate { get; set; }

        [DataType(DataType.Date), DisplayFormat(DataFormatString = @"{0:dd\/MM\/yyyy}",
           ApplyFormatInEditMode = true)]
        public System.DateTime RouteArrTDate { get; set; }

        public virtual Plane Plane { get; set; }
    }
}
